### ISSUE TITLE
Escape code parameters not parsed with leading 0

### ISSUE THREAD

**Issue by WebFreak001** [TobiasFaller/vscode-vt100-syntax-highlight#12]
compare:
![grafik](https://user-images.githubusercontent.com/2035977/93739081-b0c5ed80-fbe7-11ea-8ef9-9f148e995a93.png)

the arguments for the escape codes (in this case there is `CSI 032 m`) are considered just numbers to parse in most emulators and it's not specified that there may not be a leading 0.

See https://vt100.net/emu/dec_ansi_parser#ACPAR for a state diagram describing how the parsing state machine works and descriptions for interpretation of stuff

**Comment by TobiasFaller** [comment]
Thank you for the constant feedback. I will fix this in the **Version 0.0.14** release.

**Version 0.0.13** is now published and I hope the issues with the low contrast on light themes are fixed.

**Comment by TobiasFaller** [comment]
This should now be fixed in **Version 0.0.14**.
