### ISSUE TITLE
[Feature request] Search within Preview

### ISSUE THREAD

**Issue by digitalmouse** [TobiasFaller/vscode-vt100-syntax-highlight#17]
In case the Synchronous Scrolling request is not feasible, perhaps just having search available in the Preview window?  No clue how easy or hard that would be to implement, but since search is a part of normal window functionality, it probably is not rocket science.  :)

Otherwise, thanks so much for this extension!

**Comment by TobiasFaller** [comment]
@digitalmouse The synchronous scrolling should not be that hard to implement. Unfortunately, I'm busy with my master's thesis and therefore currently not able to implement it. I will work on this feature in two months, when I'm finished with the thesis.
The search in the preview could be implemented by using the search from the editor and then using the synchronous scoll to go to the same location in the preview window. Thank you for the suggestion. 👍

**Comment by TobiasFaller** [comment]
Synchronous scrolling has been implemented in version 0.0.15.
