### ISSUE TITLE
Color ESC sequences should be filtered out

### ISSUE THREAD

**Issue by jkpubsrc** [TobiasFaller/vscode-vt100-syntax-highlight#19]
The ESC sequences that set colors are recognized by the extension but these sequences are still displayed as characters, therefore making the output unreadable.

Example:

```
[92mfoobar[0m
```

Is this intended? I'm inclined to classify this as a bug as I'd expect those sequences to not be shown any more in the editor.

Without these sequences been displayed this would be a fantastic extension!

**Comment by TobiasFaller** [comment]
There is currently no known way to hide the escape characters in the editor. Use the preview feature to see the colorized text without the escape characters.

**Comment by jkpubsrc** [comment]
:-(

Thank you for your response!
