### ISSUE TITLE
Extension doesn't seem to support VT100 Line Drawing Character Set

### ISSUE THREAD

**Issue by cc-michaelu** [TobiasFaller/vscode-vt100-syntax-highlight#20]
I tried this extension in the hopes that it would allow me to render tables generated using the VT100 Alt character set for line drawing. I have developed a handy library which generates these tables, but I would like to view them in vscode. Unfortunately the rendering is unusable. Yes, the ANSI color sequences do seem to be parsed correctly, but the line draw characters are just rendered using the default character set.

I am talking about the alt set which should be used when the `ESC(0` sequence is sent, and the default restored when the `ESC(B` sequence is sent.

I am using the latest version of vscode : 
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-28-generic
```
![image](https://user-images.githubusercontent.com/85966375/154536031-e49bd359-0035-4e64-9b2e-002530f03b76.png)

**Comment by cc-michaelu** [comment]
Here is how the table looks on the console:
![image](https://user-images.githubusercontent.com/85966375/154536907-5b0534d3-09e6-4826-ae28-85a15b1d3c04.png)

**Comment by TobiasFaller** [comment]
This sounds like a rather obscure feature to me. How about using Unicode characters / utf8 instead?

**Comment by TobiasFaller** [comment]
Have a look at this article for the respective codes: https://en.wikipedia.org/wiki/Box-drawing_character
