### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by Tachi107** [TobiasFaller/vscode-vt100-syntax-highlight#21]
Hi, thanks for the great extension! Could you please consider publishing it to the [Open VSX Registry](https://open-vsx.org)? Thanks again :)

**Comment by TobiasFaller** [comment]
Yes, I'll do that as soon as I've some time.

**Comment by TobiasFaller** [comment]
Thank you for the hint.
I have now signed the necessary agreements and will additionally make all new versions available on the Open VSX Registry in the future.

**Comment by TobiasFaller** [comment]
@Tachi107 Open VSX Link: https://open-vsx.org/extension/Tobias-Faller/vt100-syntax-highlighting

**Comment by Tachi107** [comment]
Thanks!
