### ISSUE TITLE
[Feature Request?] Open the preview by default.

### ISSUE THREAD

**Issue by FabianPastor** [TobiasFaller/vscode-vt100-syntax-highlight#32]
Not sure if i can already enable it. Same as with vscode markdown, you can select to open the preview by default by adding:
```
    "workbench.editorAssociations": {
        "*.md": "vscode.markdown.preview.editor",
    },
```
To your settings.json.
Could be interesting to open the preview by default. Most of the times you only want to read logs, not really edit them.

Maybe there is another way to do it?
BTW Thank you for this Extension :3

**Comment by donottellmetonottellyou** [comment]
Would indeed love this feature, so I could use vscode as a pager
