### ISSUE TITLE
Display color in preview differs from terminal

### ISSUE THREAD

**Issue by haozhouamzn** [TobiasFaller/vscode-vt100-syntax-highlight#36]
Hi, the display color in preview and editor somehow differs from terminal. 
![Screenshot 2024-11-23 at 12 18 22](https://github.com/user-attachments/assets/97daab69-38c8-4dca-9463-6813ba0ca0ed)

In the screen shot, green `32` is somehow more brighter in editor/preview than in the terminal. Is there some setting I can make the editor color same as terminal? 
Thanks!

**Comment by TobiasFaller** [comment]
Hey @haozhouamzn,

is the option `"vt100.use-native-theme": false,` present in your configuration file?
By default it should be set to `true` and synchronize the colors with the terminal.

Best Regards,
Tobias Faller

**Comment by haozhouamzn** [comment]
@TobiasFaller Tried both `true` and `false`, no difference. 
It seems the issue is with light themes. I'm using `"workbench.colorTheme": "Quiet Light"`. 
If I switch to `dark` themes, the colors are the same in terminal & editor.
