### ISSUE TITLE
How do you open the preview panel?

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [TobiasFaller/vscode-vt100-syntax-highlight#4]
I'm a little bit "new" to vscode extensions, so I'm not exactly sure how to use every feature that's in here.

How would I use this extension to open up the "Preview" panel that's mentioned on the extension page? I didn't see any instructions on how to do so.

**Comment by TobiasFaller** [comment]
The first step is to make sure, that the selected file type is set to "vt100".
The extension will then start to colorize the opened file in the editor.
You can then either use the context menu on the file to open the preview or press the preview button at the top right of the editor (the icon with a small panel and a magnifying glass).
