### ISSUE TITLE
[Feature request] Synchronous scrolling with side preview.

### ISSUE THREAD

**Issue by TheTechOddBug** [TobiasFaller/vscode-vt100-syntax-highlight#7]
Af far as preview do not let you search, it would be great, at least, be able to search in original file and get a synchronous scrolling in the side-preview to let you find what you want to be "colorized and properly formatted" in the side where it is like that.

Great extension!!

Thank you very much in advance.

**Comment by TobiasFaller** [comment]
I assume that the synchronous scrolling could be implemented by tagging each line with an id and then using the [scrollIntoView](https://www.w3schools.com/JSREF/met_element_scrollintoview.asp) method to scroll to the line. The line number can probably transmitted by sending an event to the WebView panel.

**Comment by TobiasFaller** [comment]
Has been implemented in version 0.0.15.
